"""empty message

Revision ID: 2c9322e53c11
Revises: c25fae7eb27b
Create Date: 2020-01-04 14:01:47.347380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c9322e53c11'
down_revision = 'c25fae7eb27b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('email', table_name='cart')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('email', 'cart', ['email'], unique=True)
    # ### end Alembic commands ###
