"""empty message

Revision ID: 586568f8eba7
Revises: c23660ba2343
Create Date: 2020-01-04 16:23:30.494951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '586568f8eba7'
down_revision = 'c23660ba2343'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('berat', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cart', 'berat')
    # ### end Alembic commands ###
