"""empty message

Revision ID: 891e5e8362a9
Revises: 586568f8eba7
Create Date: 2020-01-04 17:20:45.019352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '891e5e8362a9'
down_revision = '586568f8eba7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('ongkir', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment', 'ongkir')
    # ### end Alembic commands ###
