"""empty message

Revision ID: a2ddf20ffeb3
Revises: 917e9df0125c
Create Date: 2020-01-03 21:01:50.626023

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a2ddf20ffeb3'
down_revision = '917e9df0125c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('status_cart', sa.Boolean(), nullable=False))
    op.drop_column('cart', 'status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.drop_column('cart', 'status_cart')
    # ### end Alembic commands ###
