"""empty message

Revision ID: a3fcffd8170c
Revises: b26ec7451363
Create Date: 2020-01-12 17:37:33.702103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3fcffd8170c'
down_revision = 'b26ec7451363'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('penerbit', sa.String(length=10000), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book', 'penerbit')
    # ### end Alembic commands ###
