"""empty message

Revision ID: ba727a6dfe20
Revises: 5f5b390fed87
Create Date: 2020-01-04 13:27:06.503765

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ba727a6dfe20'
down_revision = '5f5b390fed87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('book_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'cart', 'book', ['book_id'], ['id'])
    op.drop_column('cart', 'total_harga')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('total_harga', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'cart', type_='foreignkey')
    op.drop_column('cart', 'book_id')
    # ### end Alembic commands ###
