"""empty message

Revision ID: c23660ba2343
Revises: 2c9322e53c11
Create Date: 2020-01-04 16:11:00.853205

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c23660ba2343'
down_revision = '2c9322e53c11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment', 'jasa_pengiriman')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('jasa_pengiriman', mysql.VARCHAR(length=255), nullable=False))
    # ### end Alembic commands ###
