"""empty message

Revision ID: de17d1f8a432
Revises: 8aa948a5f34d
Create Date: 2020-01-03 14:38:48.969695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de17d1f8a432'
down_revision = '8aa948a5f34d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cart_id', sa.Integer(), nullable=True),
    sa.Column('nama_jalan', sa.String(length=255), nullable=False),
    sa.Column('rt_rw', sa.String(length=255), nullable=False),
    sa.Column('kelurahan', sa.String(length=255), nullable=False),
    sa.Column('kecamatan', sa.String(length=255), nullable=False),
    sa.Column('kota_kabupaten', sa.String(length=255), nullable=False),
    sa.Column('provinsi', sa.String(length=255), nullable=False),
    sa.Column('kode_pos', sa.String(length=255), nullable=False),
    sa.Column('nomor_telepon', sa.String(length=255), nullable=False),
    sa.Column('jasa_pengiriman', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['cart_id'], ['cart.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment')
    # ### end Alembic commands ###
